name: Resourcio
options:
  minimumXcodeGenVersion: 2.38.0
settings:
  base:
    SWIFT_VERSION: 6.0
    MACOSX_DEPLOYMENT_TARGET: "13.0"
targets:
  Resourcio:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Sources/Resourcio
    info:
      path: Config/Resourcio-Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.resourcio.app
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        ENABLE_HARDENED_RUNTIME: YES
        SWIFT_EMIT_LOC_STRINGS: NO
schemes:
  Resourcio:
    build:
      targets:
        Resourcio: all
    archive:
      config: Release
